### ISSUE TITLE
@列表中如果有重名用户，会有key warning

### ISSUE THREAD

**Issue by ILuZhangKun** [react-component/mentions#14]
原issue链接： https://github.com/ant-design/ant-design/issues/18435
在rc-Mentions中，
https://github.com/react-component/mentions/blob/master/src/DropdownMenu.tsx

```javascript
<MenuItem
    key={value}
    disabled={disabled}
    className={className}
    style={style}
    onMouseEnter={() => {
        setActiveIndex(index);
    }}
>
    {children}
</MenuItem>
```

value直接作为key了，没有考虑value相同（即@列表重名）的情况。

**Comment by day-day-sleep** [comment]
mentions getMentionResult  通过文本返回 选择的mention数组 不能保证useName相同的情况。现在的问题应该是option的选择项希望是useName 而不是用户不懂的userID

<Mentions.Option key={id} value={user.userName}>
           <OSSAvatar ossKey={user.avatar} ossStyle={ImageStyle.OSS_AVATAR_SMALL}  size="small" />
           <span style={{ marginLeft: 8 }}>{user.userName}</span>
</Mentions.Option>

let mention = new Set<string>();
Mentions.getMentions(content).forEach(item => {
          if (this.mentionSelectMap && this.mentionSelectMap.has(item.value)) {
                    let value = this.mentionSelectMap.get(item.value)!;
                    if (!mention.has(value)) {
                        mention.add(value.toString());
                    }
          }
 });
