### ISSUE TITLE
metions的Options正在加载时，直接按下enter会选出默认值，导致bug

### ISSUE THREAD

**Issue by AsserHong** [react-component/mentions#69]
![image](https://user-images.githubusercontent.com/9391777/124591976-864fd300-de8f-11eb-9ec1-2d0981ca6ca7.png)
当onSearch的请求没有返回时，options为一个菊花默认选项。此时按下enter键会选择默认值，但是鼠标点击菊花Option是不能选择的，此处交互不一致。

**Comment by afc163** [comment]
来个 PR？
