### ISSUE TITLE
[Feature Request] Add suffix property

### ISSUE THREAD

**Issue by dengfuping** [react-component/mentions#7]
- Hope to set suffix string when option is selected.

![2019-07-01 11-19-22 2019-07-01 11_20_09](https://user-images.githubusercontent.com/14918822/60408641-5c091200-9bf2-11e9-9e0c-6752e52d6a72.gif)

**Comment by zombieJ** [comment]
Synced:
Use `value` & `filterOption` to realize the auto fill suffix function.
