### ISSUE TITLE
Equivalent of getSuggestionsContainer prop

### ISSUE THREAD

**Issue by vijayst** [react-component/mentions#9]
I am upgrading my code from the old Mention component to the new Mentions component. I am using Mentions in a `position: fixed` element. Instead of adding the suggestions to the root DOM element, I want to add the suggestions to the fixed container. With the previous Mention component, I could do it with getSuggestionsContainer prop. But with the new mentions component, I don't have the prop and the suggestions don't render correctly. 

Is it possible to add this prop: getSuggestionsContainer?

**Comment by vijayst** [comment]
@yesmeck @zombieJ -- is this something that should be fixed? I can do a PR if we need to have this prop.

**Comment by zombieJ** [comment]
Yes. PR is welcome. Let's use `getPopupContainer` instead. We use this in other rc-component. It's time to sync api.

**Comment by vijayst** [comment]
I am not able to get `npm start` to work. Throws an error that it can't resolve 'core-js/...'. I am using Node 11.15.0.

**Comment by zombieJ** [comment]
Hmmm...remove all the lock file and use `yarn` to try again.

**Comment by vijayst** [comment]
I could not resolve the rc-tools / core-js error. But here is the commit which will fix the issue: 
https://github.com/vijayst/mentions/commit/3137fae40d87345d1b45c9ac6621fc5967456dfa

It is a simple change where there is a getPopupContainer prop passed to rc-trigger component.

**Comment by zombieJ** [comment]
You can PR for this since we have CI : )

**Comment by vijayst** [comment]
PR - https://github.com/react-component/mentions/pull/10

**Comment by vijayst** [comment]
PR - https://github.com/react-component/mentions/pull/12
